### ISSUE TITLE
Move from Mandrill

### ISSUE THREAD

**Issue by Rchristiani** [HackerYou/chalk-api#56]
Mandrill is becoming paid, look into https://www.npmjs.com/package/nodemailer instead. Send emails from server instead of depending on  3rd-party.

**Comment by yepher** [comment]
Just incase it can help here is the Mandrill migration to SparkPost [guide](https://www.sparkpost.com/mandrill-migration-guide) and this [Slack channel](http://slack.sparkpost.com) is available if you need help with the migration.

They are giving 100,000 free emails/month.
