### ISSUE TITLE
502 error on update section endpoint has resurfaced 

### ISSUE THREAD

**Issue by kristencodes** [HackerYou/chalk-api#84]

**Comment by Rchristiani** [comment]
```
/usr/share/nginx/html/api/course.js:294
		doc.lessons = model.lessons.map(lesson => lesson._id);
```

Same error as before it seems.

**Comment by Rchristiani** [comment]
This might have been solved here https://github.com/HackerYou/chalk-api/blob/master/server.js#L21-L23

I saw another error in the logs `Error: request entity too large`. This fixes that issue.
